"""
api/apps.py

App configuration for the 'api' Django app.
This file is auto-generated by startapp and rarely needs touching.
It just tells Django "hey, this app exists and here's its name."
"""

from django.apps import AppConfig


class ApiConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'api'
    verbose_name = 'UniFind API'  # Shows up in the admin panel header
