name: Build & Deploy Flutter Web

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
          channel: 'stable'

      - name: Build Flutter web
        working-directory: unifind_flutter
        run: flutter build web --base-href /~ivanovs1/UniFind/

      - name: Push built files to gh-deploy branch
        run: |
          cp .cpanel.yml unifind_flutter/build/web/.cpanel.yml
          cd unifind_flutter/build/web
          git init
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Deploy built Flutter web"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Krishita22/UniFind.git HEAD:gh-deploy
